version: "3"

services: 
  pg-nextjs:
    image: postgres:14.2
    container_name: next_app
    environment:
      POSTGRES_PASSWORD: '852147'
      POSTGRES_DB: 'nextjs-todo'
    volumes:
      - ./.docker/db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
